### ISSUE TITLE
data-separator

### ISSUE THREAD

**Issue by celine-m-s** [jens-na/jekyll-reveal#2]
Hello,

I'm using your great jekyll template using reveal.js and I have a problem. I'd like to edit my slides using markdown and to insert "---" to separate horizontal slides and "--" to separate vertical slides. I didn't find a way to do it with your template... :-(
I tried to add 

``` html
<section data-markdown data-separator="^---$" data-vertical="^--$" data-notes="^Note:">
  <script type="text/template">
    {{ content }}
  </script>
</section>
```

in _layouts > slide.html and in _slides > test.md I put : 

``` markdown

---
title: Test slide 1
description: Use another theme (moon.css) and disable the progress bar at the bottom

---
#Demo 2
--
##Some important title
```

But then when I start the server the only thing I have is a page without content (everything inside the `<script>` tag is hidden). Markdown is working but the script doesn't seem to work...
Do you know how I could do ?

Thanks!

Céline

**Comment by jens-na** [comment]
I have never used jekyll-reveal with Markdown, but you can get it working if you follow the following steps:

**1.**
Add markdown dependency for reveal.js in `_layouts/slide.html`:

``` diff

       // Optional libraries used to extend on reveal.js
       dependencies: [
+        { src: '/reveal.js/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
+          { src: '/reveal.js/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
         { src: '/reveal.js/plugin/highlight/highlight.js', async: true, callback: function() { window.hljs.initHighlightingOnLoad(); } },
         { src: '/reveal.js/lib/js/classList.js', condition: function() { return !document.body.classList; } }
       ]

```

**2.**
Afterwards you need to supress the Markdown rendering of Jekyll, because you need to let reveal.js parse your Markdown. You can do that by renaming your `test.md` into `test.html`.

**3.**
Afterwards you can edit your file `_slides/test.html` like that:

```
---
title: Test slide 1
description: Use another theme (moon.css) and disable the progress bar at the bottom
---

<section data-markdown data-separator="^\n---\n$" data-vertical="^\n--\n$">
<script type="text/template">

## Demo 2

---

Test

</script>
</section>
```

Please note that I have added the `<section>` and `<script>` tag in the file `_slides/test.html`, but it should also be possible to add them in `_layouts/slide.html` if you want to use them for all files and keep your individiual slides clean.

**Comment by jens-na** [comment]
Btw: I have opened #3 
I think it is a cool idea to have markdown support for jekyll-reveal out of the box, so I opened a pull request for myself which I will merge in a couple of days.

Can you please tell me if you have trouble get it working?

**Comment by celine-m-s** [comment]
Hello jens-na,

It works perfectly. Thank you so much for your quick answer!

**Comment by jens-na** [comment]
Great! Closed.
